/*Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.*/

#include <iostream>

int sumFibonacci()
{
	int first = 1, second = 2; // For the fibonacci numbers
	int evenSum = 2;
	while (first < 4000000 && second < 4000000)
	{
		first += second;
		second += first;
		if (first % 2 == 0)
		{
			evenSum += first;
		}
		if (second % 2 == 0)
		{
			evenSum += second;
		}
	}
	return evenSum;
}

int main()
{
	using namespace std;
	cout << "The sum of the even valued fibonacci numbers below 4000000 is " << sumFibonacci() << endl;

	system("PAUSE");
	return 0;
}